### ISSUE TITLE
TimeMenuPanel.mouseReleasedWhileTimeListIsOpen()

### ISSUE THREAD

**Issue by uxout** [LGoodDatePicker/LGoodDatePicker#62]
Hello,

i'm using LGoodDatePicker 10.3.1 and I'm having issue when setting time with a TimePicker (in a DateTimePicker).
This is the error I get : 
```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: TimeMenuPanel.mouseReleasedWhileTimeListIsOpen() Time menu list index is out of bounds. This should not happen. null
	at com.github.lgooddatepicker.zinternaltools.TimeMenuPanel.mouseReleasedWhileTimeListIsOpen(TimeMenuPanel.java:156)
	at com.github.lgooddatepicker.zinternaltools.TimeMenuPanel.access$100(TimeMenuPanel.java:20)
	at com.github.lgooddatepicker.zinternaltools.TimeMenuPanel$2.mouseReleased(TimeMenuPanel.java:75)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
How can I avoid this error?

**Comment by BlakeTNC** [comment]
Hi, can you create a minimal example of code that generates this error?
-BlakeTNC

**Comment by dangerusty** [comment]
I, too, get this error when trying to choose at time from the dropdown.

	                changeStartTime = new DateTimePicker();
			changeStartTime.setDateTimePermissive(LocalDateTime.now());
			GridBagConstraints gbc_dateTimePicker = new GridBagConstraints();
			gbc_dateTimePicker.fill = GridBagConstraints.BOTH;
			gbc_dateTimePicker.gridx = 1;
			gbc_dateTimePicker.gridy = 6;
			contentPanel.add(changeStartTime, gbc_dateTimePicker);

**Comment by dangerusty** [comment]
I checked the source and found a potential null reference opportunity. I tried once more and couldn't reproduce the issue. Maybe opening the time dropdown and picking a time can produce this if the mouse is moved away from the component at the wrong time? Such as picking a time with keyboard or something.

> If the return value of this method is null, mouse pointer is not directly above the Component.

`Point mousePositionRelativeToComponent = timeList.**getMousePosition()**;`

**Comment by dangerusty** [comment]
Oops, my error is slightly different. And I discovered its happening after I move the panel to another monitor.

> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
> 	at javax.swing.plaf.basic.BasicListUI.locationToIndex(BasicListUI.java:930)
> 	at javax.swing.JList.locationToIndex(JList.java:1590)
> 	at com.github.lgooddatepicker.zinternaltools.TimeMenuPanel.mouseReleasedWhileTimeListIsOpen(TimeMenuPanel.java:142)
> 	at com.github.lgooddatepicker.zinternaltools.TimeMenuPanel.access$100(TimeMenuPanel.java:20)
> 	at com.github.lgooddatepicker.zinternaltools.TimeMenuPanel$2.mouseReleased(TimeMenuPanel.java:75)
> 	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
> 	at java.awt.Component.processMouseEvent(Component.java:6533)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6298)
> 	at java.awt.Container.processEvent(Container.java:2236)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2294)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2280)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.awt.EventQueue$4.run(EventQueue.java:729)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
> 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
>

**Comment by BlakeTNC** [comment]
I just wanted to let you know some things.
- When it was originally developed, the time picker received less development time, and presumably has undergone less public usage, than the date picker. It's likely not as polished as the date picker.
- I have not had as much time to work on these components as I did in the past. Lately, improvements and bug fixing have come from other developers contributions.
- If you do confirm the source of this bug, and if you develop a fix, please submit a pull request.

Thank you,
-BlakeTNC
